name: caso_modificado
horizonte_horas: 24

demanda_comercio: [6,6,6,6,7,8,10,12,14,15,16,17,18,18,17,16,15,14,12,10,9,8,7,6]
demanda_ev: [0,0,0,0,0,0,5,8,10,6,4,2,0,0,0,2,4,6,8,6,4,2,0,0]
geracao_pv: [0,0,0,0,0,1,2,4,6,8,11,13,12,10,8,6,4,2,0,0,0,0,0,0]

tarifa_compra: [0.15,0.20,0.25,0.30,0.35,0.40,0.45,0.50,0.45,0.40,0.35,0.30,0.25,0.20,0.15,0.10,0.10,0.15,0.20,0.25,0.30,0.35,0.40,0.45]
tarifa_venda:  [0.08,0.08,0.08,0.08,0.08,0.08,0.08,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.08,0.08,0.08,0.08,0.08,0.08,0.08,0.08,0.08]

bess_capacidade: 24.0
bess_pot_carga_max: 6.0
bess_pot_descarga_max: 6.0
bess_soc_inicial: 12.0
bess_soc_min: 2.0
bess_soc_max: 24.0
bess_eficiencia: 0.93
